# My Jupyter Notebook on IBM Watson Studio

**Shanmuka Dondapati**

*I love data science because the data is transforming day to day which is used to learn more and more.*

***Printing of all odd numbers from 1 to 100 in just 2 lines***

In [2]:
for i in range (1,100,2):
    print(i)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99

******

Programming language:

     * C
     * C++
     * JAVA
     * Python
     * Ruby
     * Julia

# Table

|Name||AGE|
|----||---|
|Ali ||20 |
|Kris||21 |